-- DDL Statements to create the tables in Supabase

-- 1. Projects Table
CREATE TABLE public.projects (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    title text NOT NULL,
    category text NOT NULL,
    description text NOT NULL,
    image_url text NOT NULL,
    area text NOT NULL,
    location text NOT NULL,
    completion_time text NOT NULL,
    bedrooms text NOT NULL
);

-- Enable Row Level Security (RLS) for public read access
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON public.projects FOR SELECT USING (true);

-- Seed projects data
INSERT INTO public.projects (title, category, description, image_url, area, location, completion_time, bedrooms)
VALUES 
('Residential Construction', 'Residential Construction', 'Modern, energy-efficient building built with light-gauge steel frame for maximum durability and rapid assembly.', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=2070&auto=format&fit=crop', '3,200 sq.ft', 'Austin, TX', '6 Months', '4 Bedrooms'),
('Ecometal Logistics Hub', 'Commercial Warehouse', 'Spacious commercial warehouse leveraging high-strength truss systems for wide spans and high-load capacities.', 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?q=80&w=2070&auto=format&fit=crop', '45,000 sq.ft', 'Chennai, TN', '8 Months', 'Office + Warehouse'),
('Apex Innovation Office', 'Commercial Office', 'Multi-story mixed-use corporate headquarters built with pre-assembled LGS floor panels and structural frames.', 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=2070&auto=format&fit=crop', '12,500 sq.ft', 'Bangalore, KA', '5 Months', '3 Floors');


-- 2. Operators / Team Table
CREATE TABLE public.operators (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    name text NOT NULL,
    role text NOT NULL,
    badge text NOT NULL,
    image_url text NOT NULL
);

-- Enable Row Level Security (RLS) for public read access
ALTER TABLE public.operators ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON public.operators FOR SELECT USING (true);

-- Seed operators data
INSERT INTO public.operators (name, role, badge, image_url)
VALUES 
('James Kennedy', 'Construction Director', 'Construction Lead', 'https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=2000&auto=format&fit=crop'),
('Samantha Liu', 'Project Manager', 'Clinical Marketing', 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=2000&auto=format&fit=crop'),
('Marcus Turing', 'Systems Engineer', 'Systems Planner', 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=2000&auto=format&fit=crop'),
('Emily Clark', 'Architect Specialist', 'Architect Coordinator', 'https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=2000&auto=format&fit=crop');
